#ifndef HOMEWORK_C_FUNCTIONS_1_H
#define HOMEWORK_C_FUNCTIONS_1_H
int function_1(void);
int function_2(void);
int function_3(void);
int function_4(void);
int function_5(void);
int function_6(void);
int function_7(void);
int function_8(void);
int function_9(void);
int function_10(void);
int function_11(void);
int function_12(void);
#endif //HOMEWORK_C_FUNCTIONS_1_H